Parameters:
  KeyName:
    Description: Nome do par de chaves SSH para acessar a instância
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-04b70fa74e45c3917
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH PORTA 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: HTTP PORTA 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

Outputs:
  InstancePublicDNS:
    Description: EC2 Public DNS
    Value: !GetAtt MyInstance.PublicDnsName

#aws ec2 create-key-pair --key-name chavebolada --query 'KeyMaterial' --output text > chaveboladaprivada

#aws cloudformation create-stack --stack-name MeuStack --template-body file://cloudformation.yaml --parameters ParameterKey=KeyName,ParameterValue=chavebolada

#chmod 400 chaveboladaprivada

#pegar dns da instancia e mudar
#ssh -i "chaveboladaprivada" ubuntu@ec2-44-201-114-168.compute-1.amazonaws.com

#scp -i chaveboladaprivada main ubuntu@ec2-44-201-114-168.compute-1.amazonaws.com:~

#ssh -i "chaveboladaprivada" ubuntu@ec2-44-201-114-168.compute-1.amazonaws.com "sudo ./main"


#scp -i chaveboladaprivada rungoserver.service ubuntu@ec2-44-201-114-168.compute-1.amazonaws.com:~
#ssh ubuntu@ec2-44-201-114-168.compute-1.amazonaws.com 'sudo mv ~./rungoserver.service /etc/systemd/system/ && sudo systemctl enable rungoserver && sudo systemctl restart rungoserver'