name: Push-to-EC2
on:
  push:
    branches: main

jobs:
  Deploy_to_ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Build Go
      run: go build -o main ./cloudformation/main.go

    - name: Set up SSH keys
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH }}
        SSH_KNOWN_HOSTS: ${{ secrets.REMOTE_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > chaveprivada
        chmod 400 chaveprivada
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    
    - name: Deploy to EC2
      run: scp -i chaveprivada main ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~

    - name: Run EC2
      run: ssh -i chaveprivada ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "sudo ./main"
