name: Push-to-EC2
on:
  push:
    branches: main

jobs:
  AWS:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout the repository
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: us-east-1
        
        - name: CloudFormation
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          with:
            name: Meustack
            template: cloudformation/cloudformation.yaml
            parameter-overrides: "KeyName=chavebolada"
        
        - name: Get EC2 DNS
          run: |
            INSTANCE_DNS=$(aws cloudformation describe-stacks --stack-name Meustack --query "Stacks[0].Outputs[?OutputKey=='InstancePublicDNS'].OutputValue" --output text)
            echo $INSTANCE_DNS
            echo "INSTANCE_DNS=$INSTANCE_DNS" >> $GITHUB_ENV
  
  Deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: AWS

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Build Go
      run: go build -o main ./cloudformation/main.go

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH }}

    - name: Deploy
      run: rsync -a ./main ${{ secrets.REMOTE_USER }}@$${{ env.INSTANCE_DNS }}:~
    
    - name: Run
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH }}
        SSH_KNOWN_HOSTS: $${{ env.INSTANCE_DNS }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > /tmp/private_key
        chmod 400 /tmp/private_key
        ssh -i /tmp/private_key ${{ secrets.REMOTE_USER }}@$${{ env.INSTANCE_DNS }} "sudo pkill -9 main && sudo ./main &"