name: Push-to-EC2
on:
  push:
    branches: main

jobs:
  AWS:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout the repository
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: us-east-1
        
        - name: CloudFormation
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          with:
            name: Meustack
            template: cloudformation.yaml
            parameter-overrides: "KeyName=chavebolada"
        
        - name: Get EC2 DNS
          id: ec2dns
          run: |
            EC2_DNS=$(aws cloudformation describe-stacks --stack-name Meustack --query "Stacks[0].Outputs[?OutputKey=='InstancePublicDNS'].OutputValue" --output text)
            echo $EC2_DNS
            echo "EC2_DNS=$EC2_DNS" >> "$GITHUB_OUTPUT"

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.22.1'

        - name: Build Go
          run: go build -o main main.go

        - name: setup keys
          uses: kielabokkie/ssh-key-and-known-hosts-action@v1
          with:
            ssh-private-key: ${{ secrets.EC2_SSH }}
            ssh-host: ${{ steps.ec2dns.outputs.EC2_DNS }}
          
        - name: keys to file
          env:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH }}
          run: |
           echo "${SSH_PRIVATE_KEY}" > /tmp/private_key
           chmod 400 /tmp/private_key
        
        - name: Deploy
          run: scp -i "/tmp/private_key" main ${{ secrets.REMOTE_USER }}@${{ steps.ec2dns.outputs.EC2_DNS }}:~

        - name: Run
          run: ssh -i /tmp/private_key ${{ secrets.REMOTE_USER }}@${{ steps.ec2dns.outputs.EC2_DNS }} "sudo pkill -9 main && sudo ./main &"